language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
os:
  - linux
  - osx
node_js:
  - '9'
  - '8'
before_script:
  - yarn --version
  - npm --version
  - npx --version
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
